/**
 * Enterprise Configuration Example
 * 
 * This file demonstrates how to configure enterprise features.
 * Copy the configuration below and set it in your HTML template
 * or initialization script.
 * 
 * IMPORTANT: This is an example file. Do not edit this file directly.
 * Set your configuration via window.enterpriseConfig in your HTML template.
 */

// Example: Set this in your HTML template before Vue app initialization
window.enterpriseConfig = {
  // ============================================
  // BRANDING CONFIGURATION
  // ============================================
  
  // Logo URLs (paths relative to public/ or absolute URLs)
  LOGO: '/brand-assets/your-logo.svg',
  LOGO_DARK: '/brand-assets/your-logo-dark.svg',
  LOGO_THUMBNAIL: '/brand-assets/your-logo-thumbnail.svg',
  
  // Product/Brand Names
  PRODUCT_NAME: 'Your Product Name',  // Used as installation name
  BRAND_NAME: 'Your Brand',            // Used in "Powered by" text
  
  // URLs
  BRAND_URL: 'https://your-brand.com',
  WIDGET_BRAND_URL: 'https://your-brand.com',
  
  // White-Label Settings
  HIDE_FOOTER: 'true',        // Hide "Powered by" footer in widget
  HIDE_POWERED_BY: 'true',    // Alias for HIDE_FOOTER
  HIDE_HELP_DOCS: 'true',     // Hide help docs link in sidebar
  
  // ============================================
  // ANALYTICS CONFIGURATION
  // ============================================
  
  // Google Analytics
  ANALYTICS_TOKEN: 'G-XXXXXXXXXX',
  ANALYTICS_PROVIDER: 'google',
  
  // OR Segment
  // ANALYTICS_TOKEN: 'your-segment-write-key',
  // ANALYTICS_PROVIDER: 'segment',
  
  // OR Custom Analytics
  // ANALYTICS_TOKEN: 'your-custom-token',
  // ANALYTICS_PROVIDER: 'custom',
  
  // ============================================
  // THEME CONFIGURATION
  // ============================================
  
  // Enable custom theme (already enabled by default)
  ENABLE_CUSTOM_THEME: 'true',
  
  // Enable additional enterprise features
  ENABLE_ENTERPRISE_FEATURES: 'true',
  
  // ============================================
  // META CONFIGURATION
  // ============================================
  
  // Optional: Custom meta tags
  META_TITLE: 'Your Product - Customer Support Platform',
  META_DESCRIPTION: 'Your custom meta description',
};

// ============================================
// CUSTOM ANALYTICS IMPLEMENTATION EXAMPLE
// ============================================

// If using ANALYTICS_PROVIDER: 'custom', implement this:
window.enterpriseAnalytics = {
  /**
   * Initialize analytics
   * @param {string} token - Analytics token
   */
  init: (token) => {
    console.log('[Analytics] Initialized with token:', token);
    // Initialize your analytics SDK here
    // Example: yourAnalyticsSDK.init(token);
  },
  
  /**
   * Track page view
   * @param {string} path - Page path
   * @param {string} title - Page title
   */
  trackPageView: (path, title) => {
    console.log('[Analytics] Page view:', path, title);
    // Track page view
    // Example: yourAnalyticsSDK.track('page_view', { path, title });
  },
  
  /**
   * Track custom event
   * @param {string} eventName - Event name
   * @param {Object} properties - Event properties
   */
  trackEvent: (eventName, properties) => {
    console.log('[Analytics] Event:', eventName, properties);
    // Track event
    // Example: yourAnalyticsSDK.track(eventName, properties);
  },
  
  /**
   * Identify user
   * @param {string} userId - User ID
   * @param {Object} traits - User traits
   */
  identify: (userId, traits) => {
    console.log('[Analytics] User identified:', userId, traits);
    // Identify user
    // Example: yourAnalyticsSDK.identify(userId, traits);
  },
  
  /**
   * Set user properties
   * @param {Object} properties - User properties
   */
  setUserProperties: (properties) => {
    console.log('[Analytics] User properties:', properties);
    // Set user properties
    // Example: yourAnalyticsSDK.setUserProperties(properties);
  },
};

// ============================================
// EXAMPLE: Setting config in HTML Template
// ============================================

/*
In your Rails template (e.g., app/views/layouts/vueapp.html.erb),
add this before the Vue app script:

<script>
  window.enterpriseConfig = {
    LOGO: '<%= @global_config['LOGO'] %>',
    LOGO_THUMBNAIL: '<%= @global_config['LOGO_THUMBNAIL'] %>',
    PRODUCT_NAME: '<%= @global_config['INSTALLATION_NAME'] %>',
    HIDE_FOOTER: '<%= @global_config['HIDE_FOOTER'] || 'false' %>',
    ANALYTICS_TOKEN: '<%= @global_config['ANALYTICS_TOKEN'] %>',
    ANALYTICS_PROVIDER: 'google',
  };
</script>
*/

